# Generated by Django 4.2.24 on 2025-10-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_address_kit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_military",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="is_po_box",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="address",
            name="street_direction",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="address",
            name="street_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="address",
            name="street_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="address",
            name="unit_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="address",
            name="unit_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="state",
            name="code",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=165),
        ),
        migrations.CreateModel(
            name="AddressSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("provider", models.CharField(max_length=40)),
                ("raw_payload", models.JSONField(default=dict)),
                ("normalized_components", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="sources",
                        to="django_address_kit.address",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-version"),
                "unique_together": {("address", "provider", "version")},
            },
        ),
        migrations.CreateModel(
            name="AddressIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("identifier", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="identifiers",
                        to="django_address_kit.address",
                    ),
                ),
            ],
            options={
                "ordering": ("provider", "identifier"),
                "unique_together": {("provider", "identifier")},
            },
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("code", "country"), name="unique_state_code_per_country"
            ),
        ),
    ]
